max_seq_length: 1024
lora_rank: 32
alpha_mi: [0, 0.5, 1]
alpha_det: [0, 0.01, 0.1]
alpha_smi: 0
individual_reward_factor: 1
pass_reward_factor: [0, 0.5, 1]
max_z: 5
steps: 2000
model: ["llama", "qwen", "r1-qwen"]